### ISSUE TITLE
File Circularized Error results in data discarded

### ISSUE THREAD

**Issue by it-hms** [hms-networks/sc-ewon-flexy-extensions-lib#20]
This needs to be a retry. Historical time should not be advanced so that the request is retired. There needs to be a error count.

**Comment by alexjhawk** [comment]
@it-hms, 

There was a missing circularized event check for the string historical data EBD call. 

This could have resulted in the potential loss of data when:
1. Regular historical data EBD was successful
2. Then, string historical data EBD triggered a file circularized error (which was missed)

**Comment by alexjhawk** [comment]
A fix was applied as part of a rebase operation I needed to do to resolve another bug.

Now, if there is a file circularized event, both of the red highlighted (below) method calls will result in `CircularizedFileException` being thrown and the yellow highlighted (below) method call, which updates the time tracker, will not be reached.
![image](https://user-images.githubusercontent.com/51409174/198701487-699f57a5-ba9a-46d8-bd0b-8b5a27fd2069.png)

**Comment by alexjhawk** [comment]
@it-hms Was the resolution of this issue satisfactory?

**Comment by it-hms** [comment]
yeah

**Comment by alexjhawk** [comment]
The issue will be closed. Thank you for your report.
